version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.3

jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest

    steps:
      - checkout
      - gcp-cli/initialize
      - run:
          name: Start Redmine instance
          command: |
            gcloud compute instances start ${REDMINE_INSTANCE_NAME} \
            --zone=asia-northeast1-b
      - run:
          name: Set external IP address to environment variable 
          command: |
            ip_addr=$(
                       gcloud compute instances describe ${REDMINE_INSTANCE_NAME} \
                       --format='get(networkInterfaces[0].accessConfigs[0].natIP)' \
                       --zone=asia-northeast1-b \
                     )

            echo "export REDMINE_IP=${ip_addr}" >> $BASH_ENV


      - run:
          name: Install Tweepy
          command: |
            pip install tweepy
      - run:
          name: Send Job notifcation
          command: |
            python tweet.py \
            ${TWITTER_CONSUMER_KEY} \
            ${TWITTER_CONSUMER_SECRET_KEY} \
            ${TWITTER_ACCESS_TOKEN} \
            ${TWITTER_ACCESS_TOKEN_SECRET} \
            ${TWITTER_RECIPIENT}

workflows:
  version: 2
  start-redmine:
    jobs:
      - build:
          context: GCP
